package org.softcits.auth.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.softcits.auth.model.MbgUser;
import org.softcits.auth.model.MbgUserExample;

public interface MbgUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users
     *
     * @mbg.generated Wed May 23 16:30:48 CST 2018
     */
    long countByExample(MbgUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users
     *
     * @mbg.generated Wed May 23 16:30:48 CST 2018
     */
    int deleteByExample(MbgUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users
     *
     * @mbg.generated Wed May 23 16:30:48 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users
     *
     * @mbg.generated Wed May 23 16:30:48 CST 2018
     */
    int insert(MbgUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users
     *
     * @mbg.generated Wed May 23 16:30:48 CST 2018
     */
    int insertSelective(MbgUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users
     *
     * @mbg.generated Wed May 23 16:30:48 CST 2018
     */
    List<MbgUser> selectByExample(MbgUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users
     *
     * @mbg.generated Wed May 23 16:30:48 CST 2018
     */
    MbgUser selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users
     *
     * @mbg.generated Wed May 23 16:30:48 CST 2018
     */
    int updateByExampleSelective(@Param("record") MbgUser record, @Param("example") MbgUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users
     *
     * @mbg.generated Wed May 23 16:30:48 CST 2018
     */
    int updateByExample(@Param("record") MbgUser record, @Param("example") MbgUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users
     *
     * @mbg.generated Wed May 23 16:30:48 CST 2018
     */
    int updateByPrimaryKeySelective(MbgUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users
     *
     * @mbg.generated Wed May 23 16:30:48 CST 2018
     */
    int updateByPrimaryKey(MbgUser record);
}