server:
  port: 8003
  servlet.context-path: /auth-api
#security.basic.enabled: false

spring: 
    datasource:
      url: jdbc:mysql://localhost:3306/softcits_pc?useSSL=false&useUnicode=true&characterEncoding=UTF-8
      username: root
      password: 123456
      driverClassName: com.mysql.jdbc.Driver
      type: com.alibaba.druid.pool.DruidDataSource

    redis:
      host: 127.0.0.1
      port: 6379
      
USER_ID_REDIS: user_id

logging:
  file: logs/vp-rest.log #can use relative position for the log configuration
  level:
    root: info
    org.apache.ibatis: debug
    java.sql.Connection: debug
    java.sql.Statement: debug
    java.sql.PreparedStatement: debug
    com.alibaba.druid.sql: debug
    com.alibaba.druid.proxy.jdbc: info
    org.apache.ibatis.transaction.managed: info
    druid.sql: info
    org.springframework.security: debug